name: Deploy Frontend to Hetzner

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

    - name: Add Hetzner server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Hetzner
      run: |
        ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} << 'EOF'
          cd /home/${{ secrets.HETZNER_USER }}/warranty-watcher
          
          # Pull latest changes
          git pull origin main --rebase
          
          # Build images first to reduce downtime.
          docker-compose build
          
          # Stop existing containers
          docker-compose down
          
          # Start new containers
          docker-compose up -d
          
          # Remove old images to free space
          docker image prune -f
          
          # Show running containers
          docker-compose ps
          
          # Show logs for verification
          docker-compose logs --tail=50
        EOF

    - name: Verify deployment
      run: |
        ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} '
          # Check if the service is responding
          if curl -f http://localhost:3000 >/dev/null 2>&1; then
            echo "✅ Frontend deployment successful - service is responding"
          else
            echo "❌ Frontend deployment failed - service is not responding"
            exit 1
          fi
        ' 
